name: Learn GitHub Actions
on: [push]
jobs:
  Explore-GitHub-Actions:
    strategy:
      fail-fast: false
      matrix:
        #os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ['2.7', '3.6', '3.7', '3.8', 'pypy-2.7', 'pypy-3.6']
        #exclude:
        #  - os: macos-latest
        #    python-version: '3.8'
        #  - os: windows-latest
        #    python-version: '3.6'
    #runs-on: ${{ matrix.os }}
    runs-on: ubuntu-latest
    steps:
      - run: echo "Job automatically triggered by event ${{ github.event_name }}."
      - run: echo "Job running on a ${{ runner.os }} server hosted by GitHub."
      - run: echo "The branch is ${{ github.ref }} and the repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{matrix.python-version}} # Version range or exact version of a Python version to use, using SemVer's version range syntax
        #  architecture: 'x64' # optional x64 or x86. Defaults to x64 if not specified
      - run: python helloworld.py        
      - run: echo "The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "The workflow is ready to test the code."
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - run: echo "The job status is ${{ job.status }}."