name: Learn GitHub Actions
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Job automatically triggered by event ${{ github.event_name }}."
      - run: echo "Job running on a ${{ runner.os }} server hosted by GitHub."
      - run: echo "The branch is ${{ github.ref }} and the repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v2
      - run: echo "The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "The workflow is ready to test the code."
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - run: echo "The job status is ${{ job.status }}."